package bank.impl;

public enum TypesImpl{
	DATETIMEIMPL, ACCOUNTIMPL, TRANSACTIONIMPL, TRANSACTIONACCOUNTTARGET, TRANSACTIONACCOUNTSOURCE, PERSONIMPL, COMPANYIMPL, BANKIMPL, BANKPERSONCUSTOMER, BANKCOMPANYCUSTOMER, BANKACCOUNTSAVINGSACCOUNT, BANKTRANSACTIONMONEYTRANSFER, BANKACCOUNTCHECKINGACCOUNT, BANKPERSONCONSULTANT,
}
