package bank.impl;

public enum TypesImpl{
	PERSONIMPL, COMPANYIMPL, TRANSACTIONIMPL, TRANSACTIONACCOUNTTARGET, TRANSACTIONACCOUNTSOURCE, BANKIMPL, BANKTRANSACTIONMONEYTRANSFER, BANKPERSONCONSULTANT, BANKACCOUNTCHECKINGACCOUNT, BANKPERSONCUSTOMER, BANKCOMPANYCUSTOMER, BANKACCOUNTSAVINGSACCOUNT, DATETIMEIMPL, ACCOUNTIMPL,
}
