package bank.impl;

public enum TypesImpl{
	TRANSACTIONIMPL, TRANSACTIONACCOUNTSOURCE, TRANSACTIONACCOUNTTARGET, COMPANYIMPL, DATETIMEIMPL, ACCOUNTIMPL, PERSONIMPL, BANKIMPL, BANKTRANSACTIONMONEYTRANSFER, BANKACCOUNTSAVINGSACCOUNT, BANKACCOUNTCHECKINGACCOUNT, BANKPERSONCONSULTANT, BANKCOMPANYCUSTOMER, BANKPERSONCUSTOMER,
}
