package bank;

public enum Types {
	PERSON, COMPANY, TRANSACTION, TRANSACTIONTARGET, TRANSACTIONSOURCE, BANK, BANKMONEYTRANSFER, BANKCONSULTANT, BANKCHECKINGACCOUNT, BANKCUSTOMER, BANKSAVINGSACCOUNT, DATETIME, ACCOUNT,
}
