package bank;

public enum Types {
	ACCOUNT, BANK, BANKMONEYTRANSFER, BANKSAVINGSACCOUNT, BANKCONSULTANT, BANKCUSTOMER, BANKCHECKINGACCOUNT, TRANSACTION, TRANSACTIONTARGET, TRANSACTIONSOURCE, DATETIME, PERSON, COMPANY,
}
