package bank;

public enum Types {
	TRANSACTION, TRANSACTIONSOURCE, TRANSACTIONTARGET, COMPANY, DATETIME, ACCOUNT, PERSON, BANK, BANKMONEYTRANSFER, BANKSAVINGSACCOUNT, BANKCHECKINGACCOUNT, BANKCONSULTANT, BANKCUSTOMER,
}
